services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    volumes:
    - ./:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=mysql"
      - "XDG_CONFIG_HOME=/app"
    ports:
    - "80:80"
    links:
      - php-fpm
      - node
    networks:
      - my-net

  php-fpm:
    build:
      context: ./docker/php/prod/php-fpm
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=mysql"
      - "REDIS_PORT=6379"
      - "REDIS_HOST=redis"
    links:
      - mysql
      - node
    networks:
      - my-net

  mysql:
    image: mysql:8.0
    volumes:
    - ./DBDocker:/var/lib/mysql
    ports:
      - "8101:3306"
    networks:
      - my-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_HOST=mysql
      - UPLOAD_LIMIT=64M
    restart: always
    ports:
      - 81:80
    networks:
      - my-net

  node:
    image: node:18-alpine
    ports:
        - "3000:3000"
    volumes:
    - ./:/var/www
    working_dir: /var/www
    tty: true
    networks:
      - my-net

networks:
  my-net:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400
