services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    volumes:
    - ./:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=mysql"
      - "XDG_CONFIG_HOME=/app"
    ports:
    - "8080:80"
    links:
      - php-fpm
      - node

  php-fpm:
    build:
      context: ./docker/php/dev/php-fpm
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=mysql"
      - "REDIS_PORT=6379"
      - "REDIS_HOST=redis"
      - "PHP_IDE_CONFIG=serverName=Docker"
    links:
      - mysql
      - node
    extra_hosts:
        - "host.docker.internal:host-gateway"

  php-cli:
    build:
      context: ./docker/php/dev/php-cli
      dockerfile: Dockerfile
    volumes:
    - ./:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=mysql"
      - "COMPOSER_MEMORY_LIMIT=-1"
    links:
      - mysql
    tty: true

  mysql:
    image: mysql:8.0
    volumes:
    - ./DBDocker:/var/lib/mysql
    ports:
    - "33061:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_HOST=mysql
      - UPLOAD_LIMIT=64M
    restart: always
    ports:
      - 8081:80

  node:
    image: node:18-alpine
    ports:
        - "3000:3000"
    volumes:
    - ./:/var/www
    working_dir: /var/www
    tty: true

  redis:
      image: redis:latest
      ports:
          - "6379:6379"
